### ISSUE TITLE
Jumpers dont rotate with the controller

### ISSUE THREAD

**Issue by Dollehz** [ceoloide/ergogen-footprints#1]
When the niceNano controller is at an angle the jumper pads stay oriented horizontal.

![image](https://github.com/ceoloide/ergogen-footprints/assets/66185002/d88a703f-f2b9-41ec-a7d5-2cc28ab46ee7)

**Comment by ceoloide** [comment]
Thanks for reporting! I believe the rotation parameter.is missing, will modify ASAP.

I am creating a test / demo board for the footprints to uncover problems like these at https://github.com/ceoloide/ergogen-footprints-demo and will soon link it to this repo. If you have any advice on what to test for, let me know. I plan to fabricate the board to validate footprints in real life.

**Comment by ceoloide** [comment]
I've committed the changes necessary to enable dynamic rotation for all elements of the footprint, since silkscreen and labels were also not rotating.

To update the submisule and get the latest code, I use this command:

```bash
git submodule update --init --remote
```

Will track this for other footprints in an another issue. Thank you so much for reporting it!

Here's a preview of the change:
![Screenshot_20240220-204211](https://github.com/ceoloide/ergogen-footprints/assets/60667061/6d13b289-353a-4f57-b65a-d95e68bd8553)
